# Generated by Django 4.1.3 on 2022-11-09 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Corner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("longtitude", models.FloatField(default=0)),
                ("lattitude", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("total_space", models.DecimalField(decimal_places=0, max_digits=3)),
                ("occopied_space", models.DecimalField(decimal_places=0, max_digits=3)),
                ("price", models.DecimalField(decimal_places=0, max_digits=7)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("area", models.ManyToManyField(to="parking_lot.corner")),
            ],
        ),
    ]
